export const projects = [
  {
    title: 'Blockchain Dapp web 3',
    description: "Tis project is created Using React,Solidity,Tailwind & Hardhat.This is a web3 application that runs on etherium blockchain.the main functionality is that a user can make transactions between diffrent users and the transaction details will be recorded in there account ih has  a stunning design and much more",
      image: '/images/web1.png',
      tags: ['Tailwind', 'Solidity', 'Reactjs', 'Hardhat'],
    website: 'https://transactcyptoweb3.netlify.app/',
    demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_blockchain-reactjs-project-activity-6968143819783483392-U1jM?utm_source=share&utm_medium=member_desktop',
    visit: 'https://github.com/kibomamoses/Web3-Blockchain-App',
    id: 0,
  },
  {
    title: 'NFT Marketplace',
    description:" This is a is a non-fungible token (NFT) marketplace where users can buy, sell, or create NFTs. It is a noncustodial platform, allowing users full control and access to their cryptocurrency wallets. Users interact directly with other users to buy or sell an NFT or a bundle of NFTs.Its a  Web 3.0 App developed using Next JS, Sanity.io, thirdweb, Tailwind CSS, and Vercel 🔥.",
    image: '/images/nft.png',
    tags: ['NextJs', 'Thirdweb', 'Sanity', 'NFTs'],
    website: 'https://nft-marketplace-dhgz2dklv-kibomamoses.vercel.app/',
    demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_nextjs-javascriptdeveloper-web3-activity-6973669498419576832-u9na?utm_source=share&utm_medium=member_android',
    visit: 'https://github.com/kibomamoses/NFT-Marketplace',
    id: 1,
  },
  {
    title: 'LeoTube',
    description: "This is a Master modern web development by building a responsive React JS application consisting of stunning video sections, custom categories, channel pages, and, most importantly, you can play videos straight from your YouTube Clone App!.",
      image: '/images/leo.png',
      tags: ['Reactjs', 'RapidAPI', 'Material UI'], 
      website: 'https://leotube.netlify.app/',
      demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_reactjs-materialui-ui-activity-6969886168838467584-jSE_?utm_source=share&utm_medium=member_desktop',
      visit: 'https://github.com/kibomamoses/LeoTube',
    id: 2,
  },
  {
    title: 'Leopards Ecommerce',
    description: ". This  e-commerce application includes modern design and animations, the ability to add and edit products on the go using a Sanity, all advanced cart, and checkout functionalities, and most importantly, the complete integration with Stripe so that you can cover real payments.",
    image: '/images/lo2.png',
    tags: ['NextJs', 'Sanity', 'Stripe', 'Tailwind'],
    website: 'https://bright-pika-6e829f.netlify.app/',
    demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_javascriptdeveloper-react-ecommerce-activity-6966662970160373760-YFVY?utm_source=share&utm_medium=member_desktop',
    visit: 'https://github.com/kibomamoses/Ecomerce-with-Nextjs-and-sanity',
    id: 3,
  },
  {
    title: 'Hoobank',
    description: "This is a responsive React JS application consisting of a stunning hero section, high-quality assets and gradients, business stats, reusable feature sections with call-to-action buttons, testimonials, and more! ",
    image: '/images/hoo.png',
    tags: ['Reactjs','Tailwind'],
    website: 'https://leopardsbank.netlify.app/',
    demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_reactjs-ux-ui-activity-6967783963733975041-jFh8?utm_source=share&utm_medium=member_desktop',
    visit: 'https://github.com/kibomamoses/UI-UX-in-React-JS-with-Tailwind',
    id: 3,
  },
  {
    title: 'Academic Writing Websites',
    description: "This is a website selling writing websites where a user can freelance they can choose projects send a bid and earn persive income",
    image: '/images/ac.png',
    tags: ['NextJs', 'Sanity', 'Stripe', 'Tailwind'],
    website: 'https://executivewritingthemes.com/',
    demo: 'https://www.linkedin.com/posts/moses-kiboma-50b677200_javascriptdeveloper-react-ecommerce-activity-6966662970160373760-YFVY?utm_source=share&utm_medium=member_desktop',
    visit: 'https://github.com/kibomamoses/Ecomerce-with-Nextjs-and-sanity',
    id: 3,
  },
  
];

export const TimeLineData = [
  { year: 2019, text: 'Started my journey', },
  { year: 2020, text: 'Worked as a freelance developer', },
  { year: 2021, text: 'Founded JavaScript Mastery', },
  { year: 2022, text: 'Shared my projects with the world', },
  { year: 2023, text: 'Started my own platform', },
];